### ISSUE TITLE
Call your Params what they are

### ISSUE THREAD

**Issue by jzornow** [SonderMindOrg/sober_swag#13]
Similar to the the issue that I opened up about Blueprints (#12) let's call your params objects what they are instead of calling them structs. It will make it clearer to new users what's going on here. 

I'd even extend it to `Parameters`

**Comment by AnthonySuper** [comment]
Do you mind if I change this to `Input`? While they're most often used as parameters, they're really a generalized "input" type that can parse basically anything, so I think that term is more correct. I'd maybe even extend this to call it them `InputObject`, since they're designed to parse an object (you can have inputs that are just a single item, for example, which are *not* sublcasses of `SoberSwag::Struct` yet)

**Comment by jzornow** [comment]
Totally cool that. I like `Input` or `InputObject`. I think the latter's good if you're using `ObjectSerializer` for the outputs.
