### ISSUE TITLE
Don't use `sober_name`. Call the external name `name` instead.

### ISSUE THREAD

**Issue by jzornow** [SonderMindOrg/sober_swag#14]
This is more intuition and codebase navigation. Giving things cute names is cute but it can hurt folks ability to navigate codebases and examples. Call this `name`, `identifier`, `key`, or something like that.

**Comment by AnthonySuper** [comment]
We can't use the name `name` as some things we want to name (notably anything to do with `SoberSwag::Struct`) are actually *classes*, and this conflicts with [`Module#name`](https://ruby-doc.org/core-2.5.3/Module.html#method-i-name) in Ruby. Since these are external names, could we possibly call them `external_name` instead?

**Comment by jzornow** [comment]
How about `identifier`?

**Comment by AnthonySuper** [comment]
That works for me.

**Comment by AnthonySuper** [comment]
Resolved.
