### ISSUE TITLE
Use nilable instead of optional for Output objects

### ISSUE THREAD

**Issue by connorshea** [SonderMindOrg/sober_swag#26]
When defining output objects, you can make the fields `optional`, but really they should probably be called `nilable`:

```ruby
FooBarOutput = SoberSwag::OutputObject.define do
  identifier 'FooBarResponse'

  field :id, primitive(:Integer)

  # `optional` should be `nilable` on output objects?
  field :error, FooBarErrorOutput.optional do |object|
    object.response.try(:[], 'error')
  end
end
```

**Comment by AnthonySuper** [comment]
[dry-types uses `.optional`](https://dry-rb.org/gems/dry-types/0.15/optional-values/), and I think keeping that for consistency is probably a good idea (since input objects are based on dry-types, so it would be `optional` there). However, I think adding an alias to both input and output objects probably makes sense?

**Comment by connorshea** [comment]
An alias would be good.
